### ISSUE TITLE
시퀄라이즈 모델 만들기

### ISSUE THREAD

**Issue by uhgenie7** [uhj1993/clone_twitter#11]
# 개요
시퀄라이즈 모델 만들기
# 내용
- 모델은 단수로 만든다 (ex: user.js)
- 시퀄라이즈는 table을 model이라고 부른다 `module.exports = (sequelize, DataTypes) => {}`
- 첫 번째 객체: define('User') : user는 모델 이름. 모델 이름이 자동으로 소문자, 복수가 되어 mysql에 저장된다. (User -> users)
  - id는 mysql에서 자동으로 적어주므로 코딩하지 않아도 됨.
- 두번째 객체: user model에 대한 세팅. 한글 저장 방법.
   charset: "utf8",
   collate: "utf8_general_ci", //한글 저장
   charset: "utf8mb4",
   collate: "utf8mb4_general_ci", //이모티콘 사용
- table간 관계가 있는 것들은 associate 에 적어준다.

# 참고
- 관계들이 많기 때문에 mysql은 관계형 데이터베이스라고 한다.
- define의 두 번째 매개변수에는, 컬럼(세로)들에 대한 것들을 적는다. email만 쭉, nickname만 죽
- 실제 data는 row라고 한다.

**Comment by uhj1993** [comment]
- define의 컬럼에는 조건을 정해주어야 한다. 
  - `type: DataTypes.STRING(30)` 문자열이고 30글자 이내
  - allowNull: false // false면 필수
  - unique: true, // 고유한 값인가?
  - string, text, boolean, integer, float, datetime ...
